version: '2'

services:
  jenkins:
    container_name: jenkins-docker
    build:
      context: ./jenkins/
    volumes:
      - ./data/jenkinsdata:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8080:8080'
      - '50000:50000'
  confluence:
    depends_on:
      - postgresql-confluence
    container_name: confluence
    build:
      context: ./confluence/
      args:
        CONFLUENCE_VERSION: 7.0.3
    volumes:
      - ./data/confluencedata/data:/var/atlassian/confluence
    ports:
      - '8888:8090'
      - '8091:8091'
    environment:
      - CONFLUENCE_DB_HOST=postgresql-confluence
      - CONFLUENCE_DB_PORT=5432
      - CONFLUENCE_DB_USER=confluence
      - CONFLUENCE_DB_PASSWORD=confluence
      - CATALINA_OPTS=-Xms256m -Xmx1g
      - CONFLUENCE_PROXY_NAME=
      - CONFLUENCE_PROXY_PORT=
      - CONFLUENCE_PROXY_SCHEME=
      - CONFLUENCE_DELAYED_START=
      - CONFLUENCE_CONFIG_PROPERTY1=hibernate.connection.driver_class
      - CONFLUENCE_CONFIG_VALUE1=org.postgresql.Driver
      - CONFLUENCE_CONFIG_PROPERTY2=hibernate.connection.password
      - CONFLUENCE_CONFIG_VALUE2=confluence
      - CONFLUENCE_CONFIG_PROPERTY3=hibernate.connection.url
      - CONFLUENCE_CONFIG_VALUE3=jdbc:postgresql://db:5432/confluence
      - CONFLUENCE_CONFIG_PROPERTY4=hibernate.connection.username
      - CONFLUENCE_CONFIG_VALUE4=confluence
  postgresql-confluence:
    image: blacklabelops/postgres
    container_name: postgresql-confluence
    volumes:
      - ./data/confluencedata/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=confluence
      - POSTGRES_PASSWORD=confluence
      - POSTGRES_DB=confluence
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
  jira:
    depends_on:
      - postgresql-jira
    container_name: jira
    build:
      context: ./jira/
    volumes:
      - ./data/jiradata/data:/var/atlassian/jira
    ports:
      - '9999:8080'
    environment:
      - 'JIRA_DATABASE_URL=postgresql://jira@postgresql-jira/jira'
      - 'JIRA_DB_PASSWORD=jira'
      - 'JIRA_DB_USER=jira'
      - 'SETENV_JVM_MINIMUM_MEMORY=512m'
      - 'SETENV_JVM_MAXIMUM_MEMORY=1024m'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
  postgresql-jira:
    image: blacklabelops/postgres
    container_name: postgresql-jira
    volumes:
      - ./data/jiradata/db:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=jira'
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=jira'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
